In [1]:
import numpy as np

## Numpy: introducción
Numpy es una librería que introduce estructuras de arreglos para realizar operaciones matemáticas básicas.

### Arreglos

Los arreglos son colecciones de elementos del mismo tipo. En numpy los elementos son de tipo *dtype*.
* **Dimension/rank**: número de ejes o índices necesarios para seleccionar un elemento del arreglo.
* **Shape**: una tupla que representa el número de elementos en cada dimensión.

Los arreglos de una dimensión se conocen como vectores; los arreglos de dos dimensiones son matrices; y los arreglos de tres o más dimensiones se llaman tensores.

### `ndarray`
La clase `ndarray` tiene múltiples funciones para crear arreglos. Numpy almacena un objeto con los siguientes campos:
* dtype: el tipo de dato.
* dimensions: número de dimensiones.
* strides: una tupla con el número de bytes necesarios para *avanzar* en una dimensión.
* data: el objeto.

### `Array()`
La función `array()` recibe un argumento y devuelve un arreglo tipo `ndarray`.
```python
np.array(sequence) # Secuencia, p. ej. listas, tuplas, ...
```
Los siguientes son arreglos de una, dos y tres dimensiones.

In [2]:
np.array([1,10,20])

array([ 1, 10, 20])

In [3]:
m = np.array([[1,2,3,4],[10,11,12,13],[20,21,22,23]])
m

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [4]:
t = np.array([[[1,2,3,4],[10,11,12,13],[20,21,22,23]],[[101,102,103,104],[110,111,112,113],[120,121,122,123]]])
t

array([[[  1,   2,   3,   4],
        [ 10,  11,  12,  13],
        [ 20,  21,  22,  23]],

       [[101, 102, 103, 104],
        [110, 111, 112, 113],
        [120, 121, 122, 123]]])

Note que los arreglos se construyen con brackets, de modo que hay brackets más internos y otros más externos. Los elementos del nivel más interno se imprimen de izquierda a derecha, y los siguientes de arriba hacia abajo. Algunos atributos de los arreglos son:
```python
array.shape
array.ndim
array.strides
```
* Los elementos de un arreglo deben ser del mismo tipo, sin embargo, las secuencias de elementos pueden ser de diferente tipo como listas, tuplas, etc.
* Si se utiliza el argumento `dtype='object'` una serie de secuencias serán convertidas en un arreglo unidimensional.
```python
np.array([...], dtype='object') # Arreglo unidimensional
```

### `arange()`
La función `arange()` genera un arreglo en secuencia similar a `range()`. La función permite ingresar el tipo de elementos y un paso con punto flotante.
```python
np.arange(a, b, step, dtype='...') # Arreglo de la forma [a,b) con paso step
```

In [5]:
np.arange(1,10,.6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. , 4.6, 5.2, 5.8, 6.4, 7. , 7.6, 8.2,
       8.8, 9.4])

La función `reshape` permite reorganizar un arreglo unidimensional para crear arreglos de diferente dimensión. La función recibe una tupla de la forma *shape* para la organización. La tupla debe ser equivalente a la longitud del arreglo original.

In [6]:
teseracto = np.arange(16)
teseracto

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
teseracto.reshape(2,2,2,2) # Teseracto; 2^4 = 16

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

### `linspace()`
La función `linspace` permite crear un arreglo indicando el número de elementos de la secuencia. La función recibe como argumentos:
* **num**: número de elementos.
* **endpoint**: boolean para incluir la cota superior `b`, por default `True`.
* **retstep**: boolean para devolver el paso, por default `False`.
```python
np.linspace(a, b, num, endpoint, retstep) # Secuencia desde a hasta b con num elementos
```

In [8]:
np.linspace(1, 50, num=4, dtype='int64')

array([ 1, 17, 33, 50], dtype=int64)

## Arreglos de 0's y 1's
Para crear un arreglo con cero's o uno's utilizamos la función `zeros()` o `ones()`, respectivamente, y una tupla shape como argumento.
```python
np.zeros(shape) # Arreglo con ceros
np.ones(shape) # Arreglo con unos
```

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

La función `eye()` crea una matriz con cero's, y con uno's en la $k$-ésima diagonal. La diagonal principal cona $k=0$.
```python
np.eye(n, m, k) # Matriz de n x m con la k-esima diagonal con unos; por default k = 0
```

In [11]:
np.eye(3,3, k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Arreglos definidos por el usuario y aleatorios
La función `full()` permite crear un arreglo de forma shape con valores y tipo definidos por el usuario.
```python
np.full(shape, fill_value, dtype)
```

In [12]:
np.full((2,4), fill_value=3, dtype='int64')

array([[3, 3, 3, 3],
       [3, 3, 3, 3]], dtype=int64)

La función `empty()` genera un arreglo no inicializado, es decir, reutiliza valores generados por el hardware o sistema operativo y sus valors no son confiables. Sin embargo, es una manera rápida de generar un arreglo.
```python
np.empty(shape) # Arreglo no inicializado
```

La función `random()` genera un arreglo con valores pseudoaleatorios de forma shape.
```python
np.random.random(shape) # Arreglo aleatorio con valores entre 0 y 1
```

## Índices
Indexar un arreglo de numpy es similar a una lista de python. El índice siempre comienza en 0 de izquierda a derecha, y con -1 de derecha a izquierda.
* Para indexar uno o más elementos se utilizan comas
```python
array[x, ...] = ... # Acceder a los elementos y reasignar
```
* Para indexar un rango se utilizan colons
```python
array[start:stop:step] = ... # Acceder a una secuencia y reasignar
```
**Los arreglos se manejan siempre desde la memoria**, por lo que dos variables con una dirección de memoria relativa al mismo arreglo, ambos modificarán el mismo objeto. Para tener objetos separados se puede generar una copia:
```python
new_array = array.copy() # Crear copia
```
## Índices de matrices
Las matrices requieren de dos índices para seleccionar uno o más elementos. Como norma general pueden existir los siguientes casos:
* Indexar un elemento
```python
array[x,y] = ... # Acceder a un elemento y reasignar
```
* Indexar un arreglo con un *slice*
```python
array[x, a:b] = ... # Acceder a un arreglo unidimensional
```
* Indexar una matriz
```python
array[a:b, i:j] = ... # Acceder a una matriz
```
## Índices booleanos
Un booleano que contiene involucra un arreglo devuelve un arreglo con valores True/False.
```python
bool_array # Booleano que involucra un arreglo; retorna un arreglo con valores True/False
```
Por lo tanto, indexar un arreglo con un booleano devuelve los valores que satisfacen la condicion.
```python
new_array = array[bool_array] # Indexar bajo la condicion bool; se asigna un arreglo con los valores que satisfacen bool
```
Si se desea convertir un arreglo booleano con 1's y 0's se utiliza la función `astype(int)`:
```python
array.astype(int) # Convertir array a 1's y 0's
```
Considera que:
* Indexar arreglos con booleanos *siempre* genera una copia.
* Indexar arreglos con booleanos que involucran operados and